#!/bin/bash

this_path=$HOME/d-vscode
path=$HOME/Library/"Application Support"/Code/User/
cd "$path"

ln -s "$this_path/settings.json" "./"
ln -s "$this_path/keybindings.json" "./"

pkglist=$(cat $this_path/pkglist)
 
for var in ${pkglist[@]}
do
    code --install-extension $var
done